spring.application.name=Paymal
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/paymal
spring.datasource.username=postgres
spring.datasource.password=nosirov123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.jackson.time-zone=Asia/Tashkent
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Tashkent
recaptcha.secret-key=6Ldt31QsAAAAAM86gbCadZ7PUb1i-1xElA-XMyev
click.service.id=88049
click.merchant.id=50739
click.payment.base.url=https://my.click.uz/services/pay
click.secret.key=YOUR_CLICK_SECRET_KEY
telegram.bot.token=8471814292:AAE-7vrRl8i2Q5Onftz5f-NF7VZgIWGS7hE
telegram.group.id=5246450111
